version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:8000"
    environment:
      - DJANGO_DEBUG=1
    volumes:
      - .:/app
      - ./keys:/app/keys:ro
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
