# Generated by Django 5.2.6 on 2025-10-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='The article slug (e.g. sports.mbb.oregon)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('google_drive_url', models.URLField(blank=True, help_text="(Optional) Link to the Google Drive folder. We'll generate one if left blank.")),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('last_fetched_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('prime', 'Prime'), ('flatpages', 'Flatpages'), ('alumni', 'Alumni')], default='prime', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_date', 'slug'],
            },
        ),
    ]
