# Generated by Django 5.2.6 on 2025-10-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='google_drive_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
