# Generated by Django 5.2.7 on 2025-10-13 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_googlecredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cached_article_preview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='package',
            name='images',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='package',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_data', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('version_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
