# Generated by Django 5.2.7 on 2025-10-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_cached_article_preview_package_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='cached_article_preview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
