# Generated by Django 5.0 on 2025-11-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_package_cached_article_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-pinned', '-publish_date', 'slug']},
        ),
        migrations.AddField(
            model_name='package',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.CharField(help_text='HELP', max_length=255, unique=True),
        ),
    ]
